### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [wordpressenginetracker/wordpressenginetracker.github.io#26] opened 2024-11-20 07:35 UTC
Dear @wordpressenginetracker team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by wordpressenginetracker** [comment] 2024-12-02 21:28
Duplicate of https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/issues/22

**Closed** 2024-12-02 21:28 UTC

**Comment by Neustradamus** [comment] 2024-12-02 21:51
@wordpressenginetracker: Can you reopen?

My ticket is to convert this personnal account to an organization, not to move in another organization.
The problem is this WP Engine Tracker personal account, it is not a person.

Thanks in advance.

**Comment by Neustradamus** [comment] 2024-12-02 21:57
@wordpressenginetracker: Can you reopen?
My ticket is to convert this personnal account to an organization, not to move into another organization.
The problem is this WP Engine Tracker personal account, it is not a person.

My ticket must be reopened, it has been not solved.

Thanks in advance.

GitHub Terms of Service:
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements
